// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp4cT4bsXT6DqGlZ8iAityL6utfaegh2M',
    appId: '1:671589651622:web:dc25482adefb9495ce1067',
    messagingSenderId: '671589651622',
    projectId: 'jihc-campus',
    authDomain: 'jihc-campus.firebaseapp.com',
    storageBucket: 'jihc-campus.firebasestorage.app',
    measurementId: 'G-98J1XWSXEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQgDdlHf-1o0wTszTA1O_SWxYo2XUhEZQ',
    appId: '1:671589651622:android:be9377dbe686e377ce1067',
    messagingSenderId: '671589651622',
    projectId: 'jihc-campus',
    storageBucket: 'jihc-campus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0GoW32jcG7bdzacGP9DtR9RAHkXa1Dyc',
    appId: '1:671589651622:ios:ec227cc179503b15ce1067',
    messagingSenderId: '671589651622',
    projectId: 'jihc-campus',
    storageBucket: 'jihc-campus.firebasestorage.app',
    iosClientId:
        '671589651622-j2f3s8ttkqqchr3b332eg97a371t4ni2.apps.googleusercontent.com',
    iosBundleId: 'com.example.jihcCampusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0GoW32jcG7bdzacGP9DtR9RAHkXa1Dyc',
    appId: '1:671589651622:ios:ec227cc179503b15ce1067',
    messagingSenderId: '671589651622',
    projectId: 'jihc-campus',
    storageBucket: 'jihc-campus.firebasestorage.app',
    iosClientId:
        '671589651622-j2f3s8ttkqqchr3b332eg97a371t4ni2.apps.googleusercontent.com',
    iosBundleId: 'com.example.jihcCampusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp4cT4bsXT6DqGlZ8iAityL6utfaegh2M',
    appId: '1:671589651622:web:c67d26376a4009f5ce1067',
    messagingSenderId: '671589651622',
    projectId: 'jihc-campus',
    authDomain: 'jihc-campus.firebaseapp.com',
    storageBucket: 'jihc-campus.firebasestorage.app',
    measurementId: 'G-R0B8RP8MD9',
  );
}
